### ISSUE TITLE
New bq. style for externally-sourced displayed quotations.

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern-forum#147]
[Thread](https://forum.textpattern.io/viewtopic.php?id=48706).

I used `ind` as class example to suggest 'indirect', `bq(ind).`. But yeah, probably not the most intuitive. Bloke's suggestion for `ext` is not terrible. Maybe `cite` is better as it's more in the framework of what these things are about.

`bq(cite).`

**Comment by wion** [comment]
I've left a lot of `bq(cite).` and `bq(cite)..` around the forum. So when you get around to this, hopefully that's the class you'll use. ;)

**Comment by philwareham** [comment]
Just had a look at this, and because we use Textile Lite on the forum (for security reasons) it doesn't allow authors to assign classnames to elements. Therefore I'm not sure there is going to be a way to implement this feature, unfortunately. Sorry Destry.
