### ISSUE TITLE
bq(cite).

### ISSUE THREAD

**Issue by wion** [textpattern/textpattern-forum#217]
This came up in the forums a while ago. I didn't make an issue apparently (though I did), so doing it now.

There are many times where people like to quote external sources and use the regular `bq.` or `bq..` to do so. But this is a little confusing because that is typically known to be a quote of thread poster in the discussion, not an external source.

I had proposed using `bq(cite).` for external sources and started marking a lot of them that way in the event a different presentation for those could be made (keep it simple... serif on white would be fine; colored boxed probably not needed). But whether it's that class or another, it doesn't matter to me; `cite` seemed like an intuitive choice.

**Comment by wion** [comment]
Whoops, I did make an issue before. Marked as invalid. Just saw that. ;)

**Comment by philwareham** [comment]
'Invalid' is maybe a harsh label though - I just can't implement it because of the Textile Lite restrictions. Sorry.
