### ISSUE TITLE
StopForumSpam key on migration

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern-forum#260]
Note to self, when @petecooper migrates the forum to .com domain I will need to update the StopForumSpam [used as part of this work](https://github.com/textpattern/textpattern-forum/issues/258) API key in the forum admin panel.

**Comment by petecooper** [comment]
Haven't forgotten about this - workload is higher than expected.

**Comment by philwareham** [comment]
No problem Pete, just do it when you are ready to.

FYI upcoming FluxBB v1.6 will require a minimum PHP version of 5.6.4 - our old server doesn't meet that requirement so I won't be able to install new versions there anymore.

**Comment by philwareham** [comment]
Key changed now. Closing.
