### ISSUE TITLE
Remove AOL IM from `profile.php?section=messaging`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-forum#266]
AOL IM was retired in December 2017, it can go.

**Comment by philwareham** [comment]
Yep - I think this is addressed in the latest FluxBB version which is due soon. If not, then I’ll edit the code myself. Cheers Pete.

**Comment by philwareham** [comment]
For reference: https://github.com/fluxbb/fluxbb/pull/211

**Comment by philwareham** [comment]
This is done in our soon-to-be-live forum instance - so closing this issue.
