### ISSUE TITLE
"A non-numeric value encountered in […]viewforum.php"

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-forum#284]
Error thrown in log, cannot reproduce at the moment:

```
2019/05/31 17:29:41 [error] 14109#14109: *7173 FastCGI sent in stderr: "PHP message: PHP Warning:  A non-numeric value encountered in /var/www/vhosts/textpattern.com/forum/live/viewforum.php on line 114" while reading response header from upstream, client: 94.XXX.XX.161, server: forum.textpattern.com, request: "GET /viewforum.php?id=7 HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "forum.textpattern.com"
```

**Comment by petecooper** [comment]
OK, I can now reproduce this. Viewing any forum post list (e.g. `/viewforum.php?id=67` and `/viewforum.php?id=12&p=9`) triggers the error message.

The affected line in our code starts with `+`, whereas the original line (see https://github.com/fluxbb/fluxbb/blob/master/viewforum.php#L90) does not…extra character in the patch file, perhaps?

Line 114 in our code:

```
+		$page_head['next'] = '<link rel="next" href="https://forum.textpattern.com/viewforum.php?id='.$id.'&amp;p='.($p + 1).'" title="'.sprintf($lang_common['Page'], $p + 1).'">';
```

Line 90 in the original code:

```
$page_head['next'] = '<link rel="next" href="viewforum.php?id='.$id.'&amp;p='.($p + 1).'" title="'.sprintf($lang_common['Page'], $p + 1).'" />';
```

Lo and behold, there's a extra `+` in our patch (https://github.com/textpattern/textpattern-forum/blob/master/src/setup/patches/feature-textpattern-forum.patch#L2246):

```
++		$page_head['next'] = '<link rel="next" href="https://forum.textpattern.com/viewforum.php?id='.$id.'&amp;p='.($p + 1).'" title="'.sprintf($lang_common['Page'], $p + 1).'">';
```

I'll raise a PR.

**Comment by petecooper** [comment]
Confirming that removing the extra `+` in the live code stops the error appearing in the logs. Hurrah!

**Comment by philwareham** [comment]
Fixed

**Comment by petecooper** [comment]
https://github.com/textpattern/textpattern-forum/pull/311 has been merged, so this can be closed.
