### ISSUE TITLE
Textile'd images not working

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-forum#310]
Background: https://forum.textpattern.com/viewtopic.php?id=50362

Issue located: https://forum.textpattern.com/viewtopic.php?pid=319122#p319122 (thank you, @gocom)

Solution: https://forum.textpattern.com/viewtopic.php?pid=319116#p319116 (thank you
@jools-r)

I'm not familiar enough with .patch files to competently do this live, so deferring this to someone else.

**Comment by philwareham** [comment]
@petecooper Hi Pete - I think the issue is now fixed but please test and let me know. Cheers!

**Comment by petecooper** [comment]
Yes, fixed - thanks very much!

**Comment by jools-r** [comment]
Looks like this one has returned – see, for example: https://forum.textpattern.com/viewtopic.php?id=51244&p=3 Maybe the previous fix just needs reinstating?

**Comment by philwareham** [comment]
Probably overwritten by fours when I fiddled with forum last week. Will looking into, and fix tomorrow. Ta!

**Comment by philwareham** [comment]
@petecooper is there anything in the error logs? The fix from 2019 is still in place so it's not that (or maybe we need to revert to the pre-fix - can't remember why this issue happened in the first place).

**Comment by petecooper** [comment]
I'll check, bear with me.

**Comment by philwareham** [comment]
Fixed.

**Comment by petecooper** [comment]
Nice one @philwareham 👌🏻
