### ISSUE TITLE
`/help.php` shows a white screen

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-forum#374]
### Expected behaviour

`/help.php` should show help.

### Actual behaviour

`/help.php` shows a blank screen

### Steps to reproduce

* visit https://forum.textpattern.com/help.php

#### Additional information

First appears in logs around 2020/05/27. Error log entry example:

```
2020/06/22 11:00:45 [error] 22180#22180: *465126 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected '<<' (T_SL) in /var/www/vhosts/textpattern.com/forum/live/help.php on line 151" while reading response header from upstream, client: [SNIPPED], server: forum.textpattern.com, request: "GET /help.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "forum.textpattern.com"
```

**Comment by philwareham** [comment]
Fixed. Sorry, there was a GitHub merge conflict in the code that was deploy live.
