### ISSUE TITLE
RSS feeds not working

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-forum#420]
**Describe the bug**

RSS via `extern.php` feeds don't work.

**To reproduce**
Steps to reproduce the behaviour:
1. Use the link under the 'Official Announcements' forum

![Screenshot 2020-12-11 at 14 30 24](https://user-images.githubusercontent.com/226578/101915427-891a6c00-3bbd-11eb-97d2-da2d64fe07ec.png)

https://forum.textpattern.com/extern.php?action=feed&fid=4&type=rss

2. Note the white screen.
3. Note the following entry in the log file:

```
2020/12/11 14:23:23 [error] 16440#16440: *231446 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined method DBLayer::has_rows() in /var/www/vhosts/textpattern.com/forum/live/extern.php:371
Stack trace:
#0 {main}
  thrown in /var/www/vhosts/textpattern.com/forum/live/extern.php on line 371" while reading response header from upstream, client: IP.IP.IP.IP, server: forum.textpattern.com, request: "GET /extern.php?action=feed&fid=4&type=rss HTTP/2.0", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", h
ost: "forum.textpattern.com", referrer: "https://forum.textpattern.com/"
2
```

**Expected behaviour**
RSS via `extern.php` to work without issue.

**Screenshots**

**Additional context**
Server-side issue, likely with FluxBB or customisation of.

**Comment by philwareham** [comment]
It's probably where we commented out the stuff that exposed the forum to third party scrutiny. I'm not near computer this weekend so if you want me to look at it, it'd be next week now.

**Comment by petecooper** [comment]
Ah, of course - leave it with me, I'll have a look.

**Comment by petecooper** [comment]
Nope, that's not it. No urgency, @philwareham, I'll see what else I can find.

**Comment by petecooper** [comment]
Fixed.
