### ISSUE TITLE
Consider switching reCAPTCHA to hCaptcha

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-forum#438]
Our forum signup page includes a reCAPTCHA challenge. There are reported concerns about privacy, which should be a consideration given our previous moves as a project. hCaptcha appears to work in a very similar way, and is reportedly API-compatible.

Considerations:

* Only affects new signups, current login form does not use reCAPTCHA.
* It's not perfect, but I would hope with wider distribution it will improve.

https://docs.hcaptcha.com/switch/
https://docs.hcaptcha.com/faq/

I have no skin in the game, beyond a desire to not fill Google's coffers any further.

**Comment by philwareham** [comment]
The reCAPTCHA is a plugin by the author of FluxBB. Not sure if I have the PHP expertise to amend it to use hCaptcha instead, will take a look.

**Comment by MioVisman** [comment]
Instead of reCAPTCHA and hCaptcha, try using Copyable captcha https://fluxbb.org/resources/mods/copyable-captcha/ 
By analogy with reCAPTCHA, this extension is an addon. 
Uses cookie and css (inline in registration page).
No external services required. 
Works here https: //fluxbb.qb7.ru/forum/register.php

**Comment by philwareham** [comment]
@MioVisman thanks that seems like a nice simple solution. Will try it out in our [customized clone of FluxBB](https://github.com/textpattern/fluxbb/tree/feature-textpattern-forum).

FYI there's probably some stuff in there that would be beneficial to your FluxBB work - JSON-LD, better accessibility, etc. I will try to summarise some of the changes soon.

**Comment by philwareham** [comment]
OK, I've added and tested the Captcha alternative suggested by @MioVisman and it works.

NTS and @petecooper we may need to find a way to add a `nonce` onto the inline CSS `<script>` tag of this add-on if we end up using this on our production code and subsequently tighten the Content Security Policy rules. At the moment our forum CSP has `style-src 'self' 'unsafe-inline\' ...` so it'll work for now.

Other CSP note, we can also remove `https://www.google.com/recaptcha/ https://www.gstatic.com/recaptcha/` from our `script-src` if this goes live.

**Comment by philwareham** [comment]
One more thing: once live, we can monitor whether there is an uptick in bogus registrations. If so, then hCaptcha may be the route forward, if we want to avoid Google (and, of course, we do want to avoid Google). 😀
