### ISSUE TITLE
Mastodon profile inherits GitHub URL

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-forum#448]
**Describe the bug**
The user profile Mastodon link uses the GitHub URL:

**To reproduce**
Steps to reproduce the behaviour:
1. Go to profile social media, enter a GitHub profile URL, save it, note it's now in Mastodon field.

**Expected behaviour**
GitHub should stay in GitHub, Mastodon should be separate.

**Screenshots**

![Screenshot 2021-03-14 at 08 18 15](https://user-images.githubusercontent.com/226578/111062672-2da09880-84a2-11eb-9b07-095d4b314de0.png)

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
Latest codebase after server migration.

**Comment by philwareham** [comment]
Fixed and live.
