### ISSUE TITLE
Email notifications not sending since server migration

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern-forum#451]
Reference: https://forum.textpattern.com/viewtopic.php?id=51426

I seem to be experiencing this too. Not sure if server issue of FluxBB issue. @petecooper can you please check error logs with you get a spare moment and report back?

**Comment by petecooper** [comment]
Postfix is stuck. Please hold.

**Comment by petecooper** [comment]
Sorted. Manually processing 7x replies to Philippe now.
