### ISSUE TITLE
Manual upgrading instructions

### ISSUE THREAD

**Issue by gocom** [textpattern/textpattern-forum#58]
These are manual instructions until we get deployer up and running.

First navigate to the current clone.
## Checkout new tag

```
$ git pull
$ git checkout tags/1.0.0
```

Where the v0.2.0 is the tag you want.
## Update dependencies

Run package managers:

```
$ npm install
$ bower update
$ bundle install
$ composer update
```
## Build

```
$ grunt setup
```

The above downloads/extracts/patches FluxBB and builds assets.
## Update FluxBB

Check if FluxBB database needs updating through its GUI; visit the forum location and do any instructed steps if any.
## Clean up

```
$ grunt postsetup
```

Which removes any unnecessary leftover files used by FluxBB setup process.

Done.

**Comment by philwareham** [comment]
Updates are done manually now, which removes reliance on server-side resources that may be out of date. Closing.
