### ISSUE TITLE
[front end, cosmetic] 2x changes to links on index page

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-forum#65]
There’s a link to Textpattern CMS Issue Tracker from the forum index. Right now, it points to Google Code. It should point to `https://github.com/textpattern/textpattern/issues`.

Additionally, there's a link to textgarden.org that needs to be removed – that’s currently listed as “Textpattern CMS Themes”.

**Comment by petecooper** [comment]
The textgarden.org domain has been acquired by a marketeer, and the site runs atop WordPress.

**Comment by philwareham** [comment]
Done. [See here](https://github.com/textpattern/textpattern-com-website/commit/49a6eb07e9034bcb37843fa848d169fd5fbdaf7d). Will find a better home for themes link to point to in due course.
