### ISSUE TITLE
PHP 8.1 deprecation warnings in `php-fpm.log`

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-forum#668]
**Describe the bug**
PHP 8.1 deprecation warnings in `php-fpm.log`.

**To reproduce**
Steps to reproduce the behaviour:
1. Run Textpattern forum atop PHP 8.1
2. Note the following in `php-fpm.log`:

```
[16-Oct-2023 09:13:16] WARNING: [pool www] child 1263 said into stderr: "NOTICE: PHP message: PHP Deprecated:  mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/servers/textpattern.com/forum/live/include/utf8/mbstring/core.php on line 125"
[16-Oct-2023 09:13:16] WARNING: [pool www] child 1263 said into stderr: "NOTICE: PHP message: PHP Deprecated:  Parser::textileRestricted() is deprecated. Use Parser::parse() with Parser::setRestricted() instead. in /var/www/servers/textpattern.com/forum/live/vendor/netcarver/textile/src/Netcarver/Textile/Parser.php on line 2080"
```

**Expected behaviour**
Warning-free operation.

**Additional context**
Recent switch to PHP 8.1 has thrown these warnings, and _lots_ of them, resulting in a 24GB log file in 5 days.

**Comment by Bloke** [comment]
Oooft, looks like one for Mio Visman! Should we ping him?

**Comment by Bloke** [comment]
Oooft, looks like one for MioVisman! Should we ping him?

**Comment by petecooper** [comment]
Is the Textile issue separate? I opened the issue here since we need to properly triage it, there may be newer versions to update to first.

**Comment by philwareham** [comment]
We are using Textile 3.8.0 in the forum so I could go to a higher version (will test locally first).

**Comment by petecooper** [comment]
There's also `rev.85` from ~3 weeks go: https://github.com/MioVisman/FluxBB_by_Visman/releases/tag/1.5.11.85

`rev.84` includes some PHP 8.1 tweaks.

**Comment by philwareham** [comment]
@petecooper I am hoping I have fixed the Textile deprecation error with the commit above (which I have put live on the forum). Could somebody check by creating a new user and trying to post an image (it should prevent displaying images by new users).

I'll also check the MioVisman FluxBB fork for additional PHP8 fixes as suggested by Pete - although depending on how much the codebase has changed in that fork by findings might be limited.

**Comment by philwareham** [comment]
Ignore that - the images are broken again, so I'll revert and try to work out what the correct method and format is.

**Comment by philwareham** [comment]
@bloke can you look at this code and give any pointers? FYI that changes in that commit didn't work: https://github.com/textpattern/fluxbb/commit/f14149cc1b7ac36f83a622328b591967763df87f

**Comment by Bloke** [comment]
Sure, you can't `return` twice from a function.

The methods are chainable so you should be able to do this:

```
return $textile->setRestricted(true)->setImages(false)->parse($text);
```

**Comment by philwareham** [comment]
Thanks. I have simply removed that code now anyway as `PUN_NEW_MEMBER` never seems to be defined (might have been deprecated or changed at some point in the past).

All registered users can post images now (and seems to have been the case for a while).

**Comment by philwareham** [comment]
OK @petecooper I think I have now patched the forum to fix those two log errors - can you let me know later if the log is clear now? Ta!

**Comment by petecooper** [comment]
OP warnings appear to have gone - there's a new one:

```
2023/10/16 12:17:46 [error] 18931#18931: *307 FastCGI sent in stderr: "www/servers/textpattern.com/forum/live/include/functions.php on line 841
PHP message: PHP Deprecated:  mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/servers/textpattern.com/forum/live/include/functions.php on line 841
```

**Comment by philwareham** [comment]
OK, how about now?

**Comment by petecooper** [comment]
Jackpot! Thank you @philwareham & @Bloke!
