### ISSUE TITLE
Forum CSS not loading on Tor

### ISSUE THREAD

**Issue by petecooper** [textpattern/textpattern-forum#673]
**Describe the bug**
Unstyled forum on Tor.

**To reproduce**
Steps to reproduce the behaviour:
1. Access the forum via Tor.

**Expected behaviour**
Styled forum on Tor.

**Screenshots**

<img width="1123" alt="Screenshot 2023-11-24 at 09 59 59" src="https://github.com/textpattern/textpattern-forum/assets/226578/10a379bd-bb6f-45e3-9a4d-06a32918bd34">

**Desktop (please complete the following information):**
 - OS: macOS 14.1.1
 - Browser: Tor
 - Version: 13

**Smartphone (please complete the following information):**

**Additional context**

Works fine on Firefox, so presumably a security consideration with Tor.

**Comment by Bloke** [comment]
Mine did exactly the same in an incognito sessions yesterday on my mobile browser (Via). Today it's fine. Weird.

**Comment by petecooper** [comment]
I think I know what this is - if you can wait until I have some spare time later I can fix today.

**Comment by petecooper** [comment]
I think this is now fixed. Nginx rip, replace & reconfigure did the trick.
