### ISSUE TITLE
Update theme links on forum, textpattern.com and wiki page to consistent wording and useful target

### ISSUE THREAD

**Issue by jools-r** [textpattern/textpattern-forum#68]
Just acting on [Peter’s request on the forum](http://forum.textpattern.com/viewtopic.php?id=46519):

* The External Textpattern Links section on [textpattern.com](http://textpattern.com) (left col at the bottom) is called “Templates” rather than “Themes” and links to a currently empty site at http://themes.textpattern.com/.
* The “Themes” link on the [forum main nav](http://forum.textpattern.com/) points to the “Creating Textpattern Themes" page (see next bullet point) not to a source of themes.
* On the [wiki page on creating themes](http://www.textpattern.net/wiki/index.php?title=Creating_Textpattern_themes) the "Themes" link in the main nav at the top points to the now defunct textgarden.org.

Suggestion: perhaps themes.textpattern.com is a good destination and just needs some interim links to actual sites with theme links until a new site is up. See Peter’s forum post for a start.

**Comment by 1zero** [comment]
Suggestion: just point all themes links to txpthemes.com where there are working themes.

**Comment by rwetzlmayr** [comment]
I've established a web server at http://themes.textpattern.com/. Redirection target could be the subject of some further discussion if anyone wants to.
