### ISSUE TITLE
Advertisements, sponsor banners?

### ISSUE THREAD

**Issue by gocom** [textpattern/textpattern-forum#9]
Should or could we integrate advertisements/sponsor banners to the forums? Something not too distracting, not huge block of images on a sidebar or a header like on the main site, but something that actually fits to the content.

Let's say, for example, an advertisement spot before the first reply on each topic (only if the topic has at least two posts), and before the last reply (when thread spawns more than two pages).

**Comment by philwareham** [comment]
This is done, but not used at the moment. Closing.
