### ISSUE TITLE
Google Custom Search crud results

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpattern-forum#90]
The Google Custom Search results are almost useless. Either the site isn't being crawled properly and needs fixing or we need to scrap it and use the in-built FluxBB search here (which, although not great, gives much better search results).

**Comment by Bloke** [comment]
The other day I struggled to find something recent that I knew existed, so I'd second fixing/scrapping it.

**Comment by philwareham** [comment]
Using FluxBB search feature now. Did implement a new Google CSE (v2) which was better than the previous (v1) implementation - but still not as clean as using the forum software itself.
